config/routes.rb
Rails.application.routes.draw do
  resources :tweeets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]

  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all.order("created_at DESC")
    @tweeet = Tweeet.new

  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterMin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice]%>
  <div class="notification is-primary global-notication">
  <p class="notice"><%=notice%></p>
  </div>
  <%end%>
  <% if flash[:alert]%>
  <div class="notification is-danger global-notication">
  <p class="alert"><%=alert%></p>
  
  <%end%>
  <nav class="navbar is-info">
  <div class="navbar-brand">
  <%= link_to root_path, class: "navbar-item" do%>
    <h1 class="tittle is-5">Twitter</h1>
<%end%>
<div class ="navbar-burger burger" data-target="navbarExample">
<span></span>
<span></span>
<span></span>
</div>
</div>
<div id="navbarExample" class="navbar-menu">
<div class="navbar-end">
<div class ="field is-grouped">
<p class="control">
<%= link_to 'New tweeet', new_tweeet_path, class:"button is-info is-inverted"%>
</p>
<p class="control">Sign Up</p>
</div>
</div>
</div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">
        <%= render 'tweeets/form'%>
        </div>
    </article>


<% @tweeets.each do | tweeet |%>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>Andy Leverenz</strong><br/>
                    <small>@webcrunch</small><br/>
                    <p><%= tweeet.tweeet %></p>
                </div>
                <nav class="level">
                    <div class="level-left is mobile">
                        <%= link_to tweeet, class:"level-item" do %>
                        <span class="icon"><i class ="fa fa-link" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_tweeet_path(tweeet), class:"level-item" do %>
                        <span class="icon"><i class ="fa fa-pencil" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to tweeet, method: :delete, data: { confirm:"Are u sure you want to delete this tweeet?" } do %>
                        <span class="icon"><i class ="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
            </div>
        </article>
    </div>
    
<% end %>
</div>

app/views/tweeets/_form.html.erb
<%= simple_form_for(@tweeet) do |f| %>
<%= f.error_notification %>
<div class="field">
<div class="control">
<%= f.input:tweeet, label:"tweeet it", input_html: { class: "textarea"}, wrapper:false, label_html: {class: "label"}, placeholder: "Compose a new tweeet..."%>
</div>
</div>
<%= f.button :submit, class: "button is-info"%>
<% end %>

app/views/tweeets/_trends.html.erb
<div class="column is-one-quarter">
<nav class="panel">
<p class="panel-heading">Trends</p>
<a class="panel-block">
Trend 1
</a>
<a class="panel-block">
Trend 2
</a>
<a class="panel-block">
Trend 3
</a>
<a class="panel-block">
Trend 4
</a>
<a class="panel-block">
Trend 5
</a>
<a class="panel-block">
Trend 6
</a>
</nav>
</div>

app/views/tweeets/_who-to-follow.erb
<div class="column">
<nav class="panel">
<p class="panel-heading">Who to follow</p>

<div class="panel-block">
<article class"media">
<div class="media-left">
<figure class="image is-32x32">
<img src="https://bulma.io/images/placeholders/64x64.png">
</figure>
</div>
<div class="media-content">
<div class="content">
<p>
<strong>Jhon Smith</strong>
<small>@jhonsmith</small>
</p>
</div>
</div>
</article>
</div>
<div class="panel-block">
<article class"media">
<div class="media-left">
<figure class="image is-32x32">
<img src="https://bulma.io/images/placeholders/64x64.png">
</figure>
</div>
<div class="media-content">
<div class="content">
<p>
<strong>Jhon Smith</strong>
<small>@jhonsmith</small>
</p>
</div>
</div>
</article>
</div>
<div class="panel-block">
<article class"media">
<div class="media-left">
<figure class="image is-32x32">
<img src="https://bulma.io/images/placeholders/64x64.png">
</figure>
</div>
<div class="media-content">
<div class="content">
<p>
<strong>Jhon Smith</strong>
<small>@jhonsmith</small>
</p>
</div>
</div>
</article>
</div>
</nav>


</div>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<section class="section">
<div class="container">
<div class="columns">

<%= render 'trends'%>
<%= render 'feed'%>
<%= render 'who-to-follow'%>
</div>
</div>
</section>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>